type Payment {
  id: String!
  sender: String!
  token_address: String!
  token_symbol: String!
  amount_raw: String!
  amount_decimal: String!
  barcode: String!
  block: Int!
  timestamp: Int!
  type: String!
}
